mysql:
    image: mysql
    ports:
        - "13306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: wilderbeuasidfjalsdfaisdfast32
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin183nso71oa
        MYSQL_DATABASE: test
java-demo:
    image: java-demo
    ports:
        - "8080:8080"
    links:
        - mysql
    environment:
        DBHOST: mysql
        DBPORT: 13306
        DBNAME: test
        DBPASSWORD: wilderbeuasidfjalsdfaisdfast32
        DBUSER: root
    command: /bin/bash -c "sleep 10; java -jar demo.jar"